### ISSUE TITLE
Hiding slideUp gives 1.0 as percentage in didNavigateToStep

### ISSUE THREAD

**Issue by mathieudebrito** [stefanceriu/SCStackViewController#10]
Hi @stefanceriu 
First of all, thank you very much for this lib, it's pretty useful !

I currently have an issue using the `navigateToStep` / `didNavigateToStep` functions :
When I want to hide the slideUp, I do :
`slideUp.navigateToStep(nil, inViewController: slideUpContentView, animated: true, completion: nil)`
But in the `didNavigateToStep`,` step.percentage` equals 1.0 although it should equals 0.0.

Plus, when I call 2x
`slideUp.navigateToStep(nil, inViewController: slideUpContentView, animated: true, completion: nil)`
the slideUp do not hide, it expands at 100%.

It's very annoying. Could you bugfix this please ? or tell me how to bugfix it ? or where to look at in order to bugfix it ? It would be very appreciated.

Thanks

**Comment by stefanceriu** [comment]
Can you tell me why you are passing nil instead of SCStackNavigationStep instance as the first parameter when the interface clearly says that it's supposed to be non null ?

```objc
- (void)navigateToStep:(nonnull SCStackNavigationStep *)step...
```

**Comment by mathieudebrito** [comment]
That's the only way I found to hide the slideUp using animations :p

**Comment by stefanceriu** [comment]
Try 

```objc
[self.stackViewController navigateToStep:[SCStackNavigationStep navigationStepWithPercentage:0.0f]
                            inViewController:slideUpContentView
                                    animated:YES
                                  completion:nil];
```

or even better 

```objc
 [self.stackViewController navigateToViewController:self.stackViewController.rootViewController
                                                      animated:YES
                                                    completion:nil];
```

**Comment by mathieudebrito** [comment]
**Interesting precision :** `nonnull` is not shown in XCode autocompletion.
```
[self.stackViewController navigateToStep:[SCStackNavigationStep navigationStepWithPercentage:0.0f]
                            inViewController:slideUpContentView
                                    animated:YES
                                  completion:nil];
```
Does not work for me : it does not hide the slideUp.

But this seems to work perfectly ! 
```
 [self.stackViewController navigateToViewController:self.stackViewController.rootViewController
                                                      animated:YES
                                                    completion:nil];
```

Thank you very much ! Reactivity++

PS : it may be interesting to have a hide() function that does it for us :)

**Comment by stefanceriu** [comment]
:+1:
